import { Modal } from '@/ui/components/Modal'
import './globals.css'
import { Inter } from 'next/font/google'
import { LogoutButton } from '@/ui/components/LogoutButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex border-b-2 h-16 fixed top-0 w-full bg-white z-50 p-4">
          <LogoutButton />
        </div>
        <div className="mt-16"></div>
        {children}
      </body>
    </html>
  )
}
